In [2]:
import numpy as np

## The NumPy Array Object

In [3]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)
print(data.nbytes)

2
(3, 2)
6
int32
24


> ### Data Type


In [6]:
# int -> int8, 16, 32, 64
# uint -> 8, 16, 32, 64
# bool
# float -> 16, 32, 64, 128
# complex -> 64, 128, 256

In [7]:
data = np.array([1, 2, 3], dtype=np.float)
data

array([1., 2., 3.])

In [8]:
data.dtype

dtype('float64')

Type casting.

In [9]:
data = np.array(data, dtype=np.int)
data

array([1, 2, 3])

In [10]:
data.dtype

dtype('int32')

In [11]:
data = np.array([1, 2, 3], dtype=np.float)
data

array([1., 2., 3.])

In [12]:
data.astype(np.int)

array([1, 2, 3])

In [13]:
d1 = np.array([1, 2, 3], dtype=np.float)
d2 = np.array([1, 2, 3], dtype=np.complex)
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [14]:
(d1 + d2).dtype

dtype('complex128')

Sometimes we should define type.

In [15]:
np.sqrt(np.array([-1, 0, 1]))

<ipython-input-15-18cc2be45d00>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1]))


array([nan,  0.,  1.])

In [16]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

> ### Order of Array Data in Memory
row-major format : keyword argument `order= 'C'`\
column-major format : keyword argument `order= 'F'` \
    default format is row-major
    
> NumPy array attribute : `ndarray.strides`  

> Example: C-order array A with shape `(2, 3)` | data type : `int32` | total memory buffer for the array : `2 × 3 × 4 = 24`

> strides attribute of this array : `(4 × 3, 4 × 1) = (12, 4)` | `F` order , the strides : `(4, 8)`

> Stride 
> <img src="oQQVI.PNG">
> [Ref](https://i.stack.imgur.com/oQQVI.png)

In [17]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
print(a.itemsize)
print(a.size)
print(a.nbytes)
print(a.strides)

4
9
36
(12, 4)


Transpose \
transpose doesn't change the data, just gives a new view of data. it means it just changes the strides.

In [19]:
b = np.array([[1, 4, 7],
              [2, 5, 8],
              [3, 6, 9]]).T
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b.strides

(4, 12)

## Creating Arrays

> ### Arrays Created from Lists and Other Array-Like Objects

In [21]:
data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [22]:
print(data.ndim)
print(data.shape)

1
(4,)


using tuple

In [23]:
data = np.array((1, 2, 3, 4))
data

array([1, 2, 3, 4])

using set

In [24]:
data = np.array({1, 2, 3, 4})
data

array({1, 2, 3, 4}, dtype=object)

> ### Arrays Filled with Constant Values

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
x1 = 8.3 * np.ones(15) # not efficient
x1

array([8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3,
       8.3, 8.3])

In [32]:
x2 = np.full(15, 8.3)
x2

array([8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3,
       8.3, 8.3])

In [34]:
x1 = np.empty(5)
x1.fill(6.9)
x1

array([6.9, 6.9, 6.9, 6.9, 6.9])

> ### Arrays Filled with Incremental Sequences

using `np.arange`

In [36]:
# np.arange(start=0, end, increment=1)
# upto but not including.

In [38]:
np.arange(2)

array([0, 1])

In [40]:
np.arange(1, 11, 3)

array([ 1,  4,  7, 10])

using `np.linspace`

In [41]:
# np.linspace(start, end, total number of points in the array)
# upto with including.

In [42]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [44]:
np.linspace(0, 10, 11, endpoint=False)

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

> ### Arrays Filled with Logarithmic Sequences

In [45]:
np.logspace(0, 3, 20) # 20 data ponits between 10**0=1 to 10**3=1000

array([   1.        ,    1.43844989,    2.06913808,    2.97635144,
          4.2813324 ,    6.15848211,    8.8586679 ,   12.74274986,
         18.32980711,   26.36650899,   37.92690191,   54.55594781,
         78.47599704,  112.88378917,  162.37767392,  233.57214691,
        335.98182863,  483.29302386,  695.19279618, 1000.        ])

In [46]:
np.logspace(0, 3, 20, base=3)

array([ 1.        ,  1.18941917,  1.41471797,  1.68269268,  2.00142693,
        2.38053557,  2.83145465,  3.36778645,  4.00570977,  4.764468  ,
        5.66694959,  6.7403785 ,  8.01713542,  9.53573458, 11.34198554,
       13.49037507, 16.04571076, 19.08507602, 22.70015534, 27.        ])

> ### Meshgrid Arrays

In [7]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)

In [8]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [9]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [50]:
x = np.array([-1.5, -1, -0.5, 0, 0.5, 1, 1.5])
y = np.array([-2, -1, 0, 1, 2])
X, Y = np.meshgrid(x, y)

In [51]:
X

array([[-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5],
       [-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5],
       [-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5],
       [-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5],
       [-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5]])

In [52]:
Y

array([[-2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2]])

In [53]:
Z = (X + Y) ** 2
Z

array([[12.25,  9.  ,  6.25,  4.  ,  2.25,  1.  ,  0.25],
       [ 6.25,  4.  ,  2.25,  1.  ,  0.25,  0.  ,  0.25],
       [ 2.25,  1.  ,  0.25,  0.  ,  0.25,  1.  ,  2.25],
       [ 0.25,  0.  ,  0.25,  1.  ,  2.25,  4.  ,  6.25],
       [ 0.25,  1.  ,  2.25,  4.  ,  6.25,  9.  , 12.25]])

___

> ### Creating Uninitialized Arrays

empty array is not empty. \
empty zeroes is not as efficient as empty arrays. so we use empty arrays.

In [54]:
np.empty(10, dtype=np.float)

array([0.90909091, 1.81818182, 2.72727273, 3.63636364, 4.54545455,
       5.45454545, 6.36363636, 7.27272727, 8.18181818, 9.09090909])

> ### Creating Arrays with Properties of Other Arrays

In [55]:
# np.ones_like, np.zeros_like, np.full_like, np.empty_like

In [56]:
def f(x):
    return np.ones_like(x)

In [57]:
x = np.array([1, 5, 8, 9, 12], dtype=complex)
f(x)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

> ### Creating Matrix Arrays

In [58]:
# np.array([[], []])

In [59]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
np.eye(5, k=-3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [62]:
np.diag(np.arange(0, 27, 5))

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0],
       [ 0,  0, 10,  0,  0,  0],
       [ 0,  0,  0, 15,  0,  0],
       [ 0,  0,  0,  0, 20,  0],
       [ 0,  0,  0,  0,  0, 25]])

## Indexing and Slicing

> ### One-Dimensional Arrays 

In [63]:
# [m=0:n=end:p=1]
# upto but not including.

In [64]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
a[0]

0

In [66]:
a[-1]

10

In [67]:
a[5]

5

In [68]:
a[-5]

6

In [69]:
a[2:-2]

array([2, 3, 4, 5, 6, 7, 8])

In [70]:
a[2:-2:2]

array([2, 4, 6, 8])

In [71]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [72]:
a[-6:]

array([ 5,  6,  7,  8,  9, 10])

In [73]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

In [74]:
a[1:8:-1]    # returns empty    # if step is negative, start must be greater than stop.(???)

array([], dtype=int32)

In [75]:
a[8:1:-1]

array([8, 7, 6, 5, 4, 3, 2])

> ### Multidimensional Arrays 

In [76]:
f = lambda m, n : n + 10 * m

In [77]:
A = np.fromfunction(f, (7,7), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25, 26],
       [30, 31, 32, 33, 34, 35, 36],
       [40, 41, 42, 43, 44, 45, 46],
       [50, 51, 52, 53, 54, 55, 56],
       [60, 61, 62, 63, 64, 65, 66]])

these sub arrays are just some views from A.

In [78]:
A[2, 3]

23

In [79]:
A[:, 3]

array([ 3, 13, 23, 33, 43, 53, 63])

In [80]:
A[:2, :4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [81]:
A[2:, 4:]

array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46],
       [54, 55, 56],
       [64, 65, 66]])

In [82]:
A[::3, ::2]

array([[ 0,  2,  4,  6],
       [30, 32, 34, 36],
       [60, 62, 64, 66]])

> ### Views 

these sub arrays are just some views from A.

In [83]:
B = A[::3, ::2]
B

array([[ 0,  2,  4,  6],
       [30, 32, 34, 36],
       [60, 62, 64, 66]])

In [84]:
A

array([[ 0,  1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25, 26],
       [30, 31, 32, 33, 34, 35, 36],
       [40, 41, 42, 43, 44, 45, 46],
       [50, 51, 52, 53, 54, 55, 56],
       [60, 61, 62, 63, 64, 65, 66]])

In [85]:
B[:, :] = 100
A

array([[100,   1, 100,   3, 100,   5, 100],
       [ 10,  11,  12,  13,  14,  15,  16],
       [ 20,  21,  22,  23,  24,  25,  26],
       [100,  31, 100,  33, 100,  35, 100],
       [ 40,  41,  42,  43,  44,  45,  46],
       [ 50,  51,  52,  53,  54,  55,  56],
       [100,  61, 100,  63, 100,  65, 100]])

it's not veiw.

In [86]:
C = B[:2, 1:].copy()
C

array([[100, 100, 100],
       [100, 100, 100]])

In [87]:
C[:, :] = -500
B[:2, 1:]

array([[100, 100, 100],
       [100, 100, 100]])

In [88]:
C

array([[-500, -500, -500],
       [-500, -500, -500]])

> ### Fancy Indexing and Boolean-Valued Indexing \

it's doesn't make a view, it's make a new array.

In [89]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [90]:
A[np.array([0, 4, 6])]

array([0. , 0.4, 0.6])

In [91]:
A[[0, 4, 6]]

array([0. , 0.4, 0.6])

In [92]:
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [93]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [94]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [95]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
indices = [1, 3, 5]

In [97]:
B = A[indices]
B

array([1, 3, 5])

In [98]:
B[0] = -200

In [99]:
B

array([-200,    3,    5])

In [100]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
A[indices] = -200

In [102]:
A

array([   0, -200,    2, -200,    4, -200,    6,    7,    8,    9])

In [103]:
A = np.arange(10)

In [104]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
B = A[A > 5]

In [106]:
B

array([6, 7, 8, 9])

In [107]:
B[0] = -500

In [108]:
B

array([-500,    7,    8,    9])

In [109]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
A[A > 5] = -500

In [111]:
A

array([   0,    1,    2,    3,    4,    5, -500, -500, -500, -500])

> ### <img src="p01.png">
> ### <img src="p02.png">
> ### <img src="p03.png">

##  Reshaping and Resizing \

reshaping and resizing just change strides.

In [112]:
data = np.array([[1, 2], [3, 4]])

In [113]:
np.reshape(data, (1, 4))    # function

array([[1, 2, 3, 4]])

In [114]:
data.reshape((1, 4))    # method

array([[1, 2, 3, 4]])

In [115]:
data.reshape(4)

array([1, 2, 3, 4])

ravel returns a view, but flatten returns a copy.

In [116]:
# np.ravel(), np.flatten()

In [117]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [118]:
data.flatten()

array([1, 2, 3, 4])

In [119]:
data.flatten().shape

(4,)

increasing dimension.

In [120]:
data = np.arange(0, 5)
data

array([0, 1, 2, 3, 4])

In [121]:
column = data[:, np.newaxis]   # function
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [122]:
column.shape

(5, 1)

In [123]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

In [124]:
row.shape

(1, 5)

using method

In [125]:
# np.expand_dims(data, axis=1) = data[:, np.newaxis]
# np.expand_dims(data, axis=0) = data[np.newaxis, :]

In [126]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

stacking

In [127]:
np.vstack((data, data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [128]:
data

array([0, 1, 2, 3, 4])

In [129]:
np.hstack((data, data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [130]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [131]:
np.hstack((data, data, data, data))

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

this function is more general than hstack and vstack.\
axis=0: vertical\
axis=1: horizontal

In [132]:
np.concatenate((data, data, data, data), axis=1)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [133]:
data = np.arange(5)

In [134]:
data = data[np.newaxis, :]
data

array([[0, 1, 2, 3, 4]])

In [135]:
np.concatenate((data, data, data, data), axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## Vectorized Expressions

Broadcasting Rule
> ### <img src="p04.png">
> ### <img src="p05.png">

> ### Arithmetic Operations
>> #### Operators for Elementwise Arithmetic Operation on NumPy Arrays
>> ### <img src = p06.PNG> 

In [136]:
x = np.array([[1, 2], [3, 4]])

In [137]:
y = np.array([[5, 6], [7, 8]])

In [138]:
x + y

array([[ 6,  8],
       [10, 12]])

In [139]:
y - x

array([[4, 4],
       [4, 4]])

In [140]:
x * y

array([[ 5, 12],
       [21, 32]])

In [141]:
x * 2

array([[2, 4],
       [6, 8]])

In [142]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [143]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [144]:
(y / 2).dtype

dtype('float64')

In [145]:
x = np.array([1 , 2, 3, 4]).reshape(2, 2)

In [146]:
x

array([[1, 2],
       [3, 4]])

In [147]:
z = np.array([1, 2, 3, 4])

can't broadcast

In [148]:
# x / z    [ERROR]

In [149]:
z = np.array([[2, 4]])

In [150]:
z.shape

(1, 2)

In [151]:
x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [152]:
zz = np.concatenate([z, z], axis=0)
print(zz)

[[2 4]
 [2 4]]


In [153]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [154]:
z = np.array([[2], [4]])

In [155]:
z.shape

(2, 1)

In [156]:
z

array([[2],
       [4]])

In [157]:
x

array([[1, 2],
       [3, 4]])

In [158]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [159]:
zz = np.concatenate([z, z], axis=1)
print(zz)

[[2 2]
 [4 4]]


In [160]:
zz

array([[2, 2],
       [4, 4]])

In [161]:
x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

*inplace operators are more efficient, cause they don;t make a new array, just update the old one.*

In [162]:
# x = x + y | x += y

> ### Elementwise Functions
>> #### NumPy Functions for Elementwise Elementary Mathematical Functions
>> ### <img src='p07.PNG'>

In [163]:
x = np.linspace(-1, 1, 11)
print(x)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [164]:
y = np.sin(np.pi * x)
print(y)

[-1.22464680e-16 -5.87785252e-01 -9.51056516e-01 -9.51056516e-01
 -5.87785252e-01  0.00000000e+00  5.87785252e-01  9.51056516e-01
  9.51056516e-01  5.87785252e-01  1.22464680e-16]


In [165]:
np.round(y, decimals=5)

array([-0.     , -0.58779, -0.95106, -0.95106, -0.58779,  0.     ,
        0.58779,  0.95106,  0.95106,  0.58779,  0.     ])

>> #### NumPy Functions for Elementwise Mathematical Operations
>> ### <img src='hello.png'>

In [166]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

*it's better to use this.*

In [167]:
np.sin(x)**2 + np.cos(x)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### *defining an elementwise function using `np.vectorize`* 
this method is not efficient, cause the function will call for every element.

In [168]:
def heaviside(x):
    return 1 if x > 0 else 0

In [169]:
heaviside = np.vectorize(heaviside)

In [170]:
x = np.linspace(-5, 5, 11)

In [171]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

#### *defining an elementwise function without using `np.vectorize`*

In [172]:
def heaviside(x):
    return 1.0 * (x > 0)

In [173]:
heaviside(x)

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

> ### Aggregate Functions
>> #### NumPy Functions for Calculating Aggregates of NumPy Arrays
>> ### <img src='01.PNG'>

In [174]:
data = np.random.normal(size=(15, 15))

In [175]:
np.mean(data)    # means data.means()

-0.007755093952420808

In [176]:
data.mean()

-0.007755093952420808

*applying aggrigate function by axis.*

In [177]:
data = np.random.normal(size=(5, 10, 15))

In [178]:
data.sum(axis=0).shape

(10, 15)

In [179]:
data.sum(axis=(0, 2)).shape

(10,)

In [180]:
data = np.arange(1, 10).reshape(3, 3)
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [181]:
data.sum()

45

In [182]:
print(data.sum(axis=0))

[12 15 18]


In [183]:
print(data.sum(axis=1))

[ 6 15 24]


> ### Boolean Arrays and Conditional Expressions
>> #### NumPy Functions for Conditional and Logical Expressions
>> ### <img src='02.PNG'>

In [184]:
# <, >, <=, >=, ==, =!

In [185]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [186]:
a < b

array([ True,  True, False, False])

In [187]:
np.all(a < b)

False

In [188]:
np.any(a < b)

True

In [189]:
x = np.array([-2, -1, 0, 1, 2])

In [190]:
x > 0

array([False, False, False,  True,  True])

In [191]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [192]:
x * (x > 0)

array([0, 0, 0, 1, 2])

some application

In [193]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [194]:
x = np.linspace(-5, 5, 11)
print(x)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]


In [195]:
pulse(x, position=-3, height=5, width=6)

array([0, 0, 5, 5, 5, 5, 5, 5, 5, 0, 0])

In [196]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [197]:
pulse(x, position=-3, height=5, width=6)

array([0, 0, 5, 5, 5, 5, 5, 5, 5, 0, 0])

other functions

In [198]:
x = np.linspace(-4, 4, 9)
print(x)

[-4. -3. -2. -1.  0.  1.  2.  3.  4.]


In [199]:
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [200]:
np.select([x < -1, x < 2, x >= 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [201]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [202]:
np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [203]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [204]:
x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

In [205]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

---

> ### Set Operations
>> #### NumPy Functions for Operating on Sets
>> ### <img src='p15.PNG'>

In [206]:
a = np.unique([1, 2, 2, 3, 3, 3])

In [207]:
a

array([1, 2, 3])

In [208]:
b = np.unique([2, 3, 3, 4, 4, 4, 5, 6, 3, 2, 4])

In [209]:
b

array([2, 3, 4, 5, 6])

In [210]:
np.in1d(a, b)

array([False,  True,  True])

In [211]:
np.in1d(b, a)

array([ True,  True, False, False, False])

In [212]:
1 in a

True

In [213]:
1 in b

False

In [214]:
np.all(np.in1d(a, b)) #subset

False

In [215]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [216]:
np.union1d(b, a)

array([1, 2, 3, 4, 5, 6])

In [217]:
np.intersect1d(a, b)

array([2, 3])

In [218]:
np.intersect1d(b, a)

array([2, 3])

In [219]:
np.setdiff1d(a, b)

array([1])

In [220]:
np.setdiff1d(b, a)

array([4, 5, 6])

> ### Operations on Arrays
>> #### NumPy Functions for Array Operations
>> ### <img src='p16.PNG'>

In [221]:
data = np.arange(9).reshape(3, 3)

In [222]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [223]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [224]:
data.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [225]:
data.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [226]:
np.fliplr(data)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [227]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [228]:
np.flipud(data)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## Matrix and Vector Operations

>> #### NumPy Functions for Matrix Operations
>> ### <img src='p17.PNG'>

In [229]:
A = np.arange(1, 7).reshape(2, 3)

In [230]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [231]:
B = np.arange(1, 7).reshape(3, 2)

In [232]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [233]:
# N * M and M * P -> N * P

In [234]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [235]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [236]:
A @ B

array([[22, 28],
       [49, 64]])

In [237]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [238]:
A = np.arange(9).reshape(3, 3)

In [239]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [240]:
x = np.arange(3)

In [241]:
x

array([0, 1, 2])

In [242]:
np.dot(A, x)

array([ 5, 14, 23])

In [243]:
A.dot(x)

array([ 5, 14, 23])

In [244]:
# Ap = BAB^-1

In [245]:
A = np.random.rand(3, 3)

In [246]:
B = np.random.rand(3, 3)

In [247]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [248]:
Ap

array([[ 17.44288745,  -8.20337041,  -3.70924408],
       [ 29.25706184, -13.97256919,  -6.23536317],
       [  9.15093173,  -3.78594904,  -1.87989551]])

In [249]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [250]:
Ap

array([[ 17.44288745,  -8.20337041,  -3.70924408],
       [ 29.25706184, -13.97256919,  -6.23536317],
       [  9.15093173,  -3.78594904,  -1.87989551]])

In [251]:
A = np.matrix(A)

In [252]:
B = np.matrix(B)

In [253]:
Ap = B * A * B.I

In [254]:
Ap

matrix([[ 17.44288745,  -8.20337041,  -3.70924408],
        [ 29.25706184, -13.97256919,  -6.23536317],
        [  9.15093173,  -3.78594904,  -1.87989551]])

In [255]:
A = np.random.rand(3, 3)

In [256]:
B = np.random.rand(3, 3)

In [257]:
type(A)

numpy.ndarray

In [258]:
A = np.asmatrix(A)

In [259]:
B = np.asmatrix(B)

In [260]:
type(A)

numpy.matrix

In [261]:
Ap = B * A * B.I

In [262]:
Ap

matrix([[ 0.1256712 , -0.19927652,  0.59107573],
        [ 1.27622432, -0.7406385 ,  1.16999556],
        [ 0.75663348, -0.50911025,  1.19380259]])

In [263]:
Ap = np.asarray(Ap)

In [264]:
Ap

array([[ 0.1256712 , -0.19927652,  0.59107573],
       [ 1.27622432, -0.7406385 ,  1.16999556],
       [ 0.75663348, -0.50911025,  1.19380259]])

In [265]:
x

array([0, 1, 2])

In [266]:
np.inner(x, x)

5

In [267]:
np.dot(x, x) # 1*N, N*1

5

In [268]:
y = x[:, np.newaxis]

In [269]:
y

array([[0],
       [1],
       [2]])

In [270]:
np.dot(y.T, y)

array([[5]])

> ### Outer product
>> #### Given two vectors
>> ### <img src='p20.PNG'> 
>> #### their outer product u ⊗ v is defined as the m × n matrix A obtained by multiplying each element of u by each element of v:
>> ### <img src='p21.PNG'> 
>> #### index notation :
>> ### <img src='p22.PNG'>
>> #### The outer product u ⊗ v is equivalent to a matrix multiplication uvT, provided that u is represented as a m × 1 column vector and v as a n × 1 column vector (which makes vT a row vector). For instance, if m = 4 and n = 3, then
>> ### <img src='p23.PNG'>
>> [Wikipedia](https://en.wikipedia.org/wiki/Outer_product#cite_note-1)

In [271]:
x = np.array([1, 2, 3])

In [272]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

> ### Kronecker product
>> #### If A is an m × n matrix and B is a p × q matrix, then the Kronecker product A ⊗ B is the pm × qn block matrix:
>> ### <img src='p18.PNG'> 
>> ### <img src='p19.PNG'> 
>> [Wikipedia](https://en.wikipedia.org/wiki/Kronecker_product)

In [273]:
np.kron(x, x) # N*1, 1*N

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [274]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [275]:
np.kron(np.ones((2, 2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [276]:
np.kron(np.identity(2), np.ones((2, 2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

> [Einstein notation](https://en.wikipedia.org/wiki/Einstein_notation#:~:text=In%20mathematics%2C%20especially%20in%20applications,formula%2C%20thus%20achieving%20notational%20brevity.&text=It%20was%20introduced%20to%20physics%20by%20Albert%20Einstein%20in%201916.)
>> ### scalar product between two vectors x and y: $x_{n}y_{n}$
>> ### matrix multiplication of A and B : $A_{mk}B_{kn}$

In [277]:
x = np.array([1, 2, 3, 4])

In [278]:
y = np.array([5, 6, 7, 8])

In [279]:
np.einsum("n, n", x, y)

70

In [280]:
np.inner(x, y)

70

In [281]:
A = np.arange(9).reshape(3, 3)

In [282]:
B = A.T

In [283]:
np.einsum("mk, kn", A , B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [284]:
np.alltrue(np.einsum("mk, kn", A , B) == np.dot(A, B))

True